### PR TITLE
Added function:   get_videos_for_playlistId()

### PR DESCRIPTION
**Pull request by jimrothstein**
Appreciate any feedback.

It does **what I want it to** but  does need:

- tests
- a bit more documentation
- more, based on feedback.
- issue #15

Thx.

### CODE REVIEW

**Comment by kevin-m-kent** [comment]
thanks for your PR and patience, I will look at these today. Sorry for the delay

**Comment by kevin-m-kent** [comment]
Thanks again for this one as well. I like the core functionality - I tested it locally and was able to succesfully get the video info. I also like the tibble function but I'm not sure where that fits in.  Maybe it could be here but the name could be more descriptive like make_video_tibble.

**Comment by kevin-m-kent** [comment]
I like what you have done. A couple of suggestions:
- We should make sure get_playlists also returns the ID, so that it can be used with the get video functions.
- It looks like get_playlists has some formatting issues with the roxygen annotations and didn't get exported properly. 

In terms of what each of these functions return, I am leaning towards not placing any filtering on the return object (like not filtering snippet fields). That way it has a lot of flexibility and can be used in multiple ways. I think this is also consistent with how @jonthegeek is approach beekeeper. 

But for now, I think it's fine if you just take a look at my two points above. Then once we merge, I can refactor a bit later so that everything is consistent.

**Comment by jimrothstein** [comment]
Fixed formattng ?get_playlists.

- get_playslist  now returns `id` (playlistid).   Youtube returns this roughly as a list with two elements, which pluck must deal with.
- list(id="abcded...", 
      list(title="xyz",  description="aldkfjf;f")
- in THIS case, I found it easier to just `unlist` (flatten).
- In general, need to think about strategy.   I think you prefer not using `fields=` which is OK with me.

**Pull request closed without merging**
